package com.example.fiap.archburgers.domain.utils;

import org.junit.jupiter.api.Test;
import java.time.LocalDateTime;
import java.time.ZoneId;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Test class for the {@link Clock} class.
 * Tests the single method localDateTime.
 */
public class ClockTest {

    /**
     * Test the {@link Clock#localDateTime()} method.
     * The method returns the current time. 
     * The purpose of this test is check if the method is able to return the current time accurately within a certain limit.
     */
    @Test
    public void testLocalDateTime() {
        Clock clock = new Clock();
        LocalDateTime before = LocalDateTime.now();
        LocalDateTime result = clock.localDateTime();
        LocalDateTime after = LocalDateTime.now();
        //Test that the localDateTime generated by Clock is after the localDateTime before the clock.localDateTime call
        assertTrue(result.isAfter(before) || result.isEqual(before));
        //Test that the localDateTime generated by Clock is before the localDateTime after the clock.localDateTime call
        assertTrue(result.isBefore(after) || result.isEqual(after));
    }
}