apiVersion: v1
kind: Service
metadata:
  name: archburgers-svc-pedidos-internal
spec:
  selector:
    app: archburgers-svc-pedidos
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
