apiVersion: apps/v1
kind: Deployment
metadata:
  name: archburgers-svc-pedidos-deployment
spec:
  selector:
    matchLabels:
      app: archburgers-svc-pedidos
  replicas: 1
  template:
    metadata:
      labels:
        app: archburgers-svc-pedidos
    spec:
      containers:
        - name: archburgers-svc-pedidos-container
          image: gomesrodris/architect-burgers-svc-pedidos:0.0.2
          ports:
            - containerPort: 8091
          env:
            - name: "archburgers.datasource.dbUrl"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-db-access-config"
                  key: "archburgers.datasource.dbUrl"
            - name: "archburgers.datasource.dbUser"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-db-access-config"
                  key: "archburgers.datasource.dbUser"
            - name: "archburgers.datasource.dbPass"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-db-access-config"
                  key: "archburgers.datasource.dbPass"

            - name: "archburgers.integration.aws.region"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-pedidos-aws-config"
                  key: "archburgers.integration.aws.region"
            - name: "archburgers.integration.cognito.userPoolId"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-pedidos-aws-config"
                  key: "archburgers.integration.cognito.userPoolId"
            - name: "archburgers.integration.cognito.clientId"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-pedidos-aws-config"
                  key: "archburgers.integration.cognito.clientId"
            - name: "archburgers.integration.cognito.clientSecret"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-pedidos-aws-config"
                  key: "archburgers.integration.cognito.clientSecret"

            - name: "archburgers.integration.cardapio.ApiUrl"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-integration-config"
                  key: "archburgers.integration.cardapio.ApiUrl"
            - name: "archburgers.integration.pagamento.ApiUrl"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-integration-config"
                  key: "archburgers.integration.pagamento.ApiUrl"
            - name: "archburgers.integration.sqs.sqsEndpoint"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-integration-config"
                  key: "archburgers.integration.sqs.sqsEndpoint"
            - name: "archburgers.integration.sqs.pagamentosEmAbertoQueueName"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-integration-config"
                  key: "archburgers.integration.sqs.pagamentosEmAbertoQueueName"
            - name: "archburgers.integration.sqs.pagamentosConcluidosQueueName"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-integration-config"
                  key: "archburgers.integration.sqs.pagamentosConcluidosQueueName"

            # Needs to be passed via env var - Pod cannot assume role in AwsAcademy
            - name: "AWS_ACCESS_KEY_ID"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-pedidos-aws-config"
                  key: "archburgers.integration.aws.AWS_ACCESS_KEY_ID"
            - name: "AWS_SECRET_ACCESS_KEY"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-pedidos-aws-config"
                  key: "archburgers.integration.aws.AWS_SECRET_ACCESS_KEY"
            - name: "AWS_SESSION_TOKEN"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-pedidos-aws-config"
                  key: "archburgers.integration.aws.AWS_SESSION_TOKEN"

          readinessProbe:
            httpGet:
              port: 8091
              path: /healthcheck
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              port: 8091
              path: /healthcheck
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
            # A common pattern for liveness probes is to use the same low-cost HTTP endpoint as for readiness probes,
            # but with a higher failureThreshold
            failureThreshold: 5
          resources:
            requests:
              cpu: 250m

