apiVersion: v1
kind: Service
metadata:
  name: archburgers-svc-pedidos-svc
spec:
  type: NodePort
  selector:
    app: archburgers-svc-pedidos
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
      nodePort: 30081
